### PR TITLE
Format option and Logfmt support

### PR DESCRIPTION
**Pull request by Unactived**
This PR adds an optional `--format` option that defaults to the current console format, and adds a logfmt logger with it.

Partially addresses #3

### CODE REVIEW

**Comment by Frky** [comment]
Thank you for the PR.
To reply to the question in #73, it is of course very fine by us if you want to PR something into **masscanned**, and even more if it addresses an issue (you or someone else has), so feel free.

Just two remarks before it get merged:

* could you run `cargo fmt` on your code?
* not to be picky, but is there a reason for `et` instead of `eth` for `ethernet` in the key you chose (for instance, https://github.com/ivre/masscanned/pull/74/files#diff-cda9af6f45f28c2fc5065bbcaa066c8273112acd55be28853780b9968f9b450aR167 but not only)? Is it to be compliant with a tool that ingest logfmt files? Or is it a personal choice?

Other than that, I'd be happy to merge your PR.

**Review by Frky — CHANGES_REQUESTED** [review]
Could you run `cargo fmt` on your code?

**Comment by Unactived** [comment]
I think I'll change et to eth_type which is indeed clearer without looking at the code or thinking about the protocol's details.

**Review by Frky — APPROVED** [review]

**Comment by Frky** [comment]
Thank you for the changes (and for the PR once again).

**Pull request merged**
