### PR TITLE
Improve proto SSH

### PR DESCRIPTION
**Pull request by Frky**

### CODE REVIEW

**Comment by p-l-** [comment]
FWIW, we should also answer to `SSH-1.99-*` packets (clients supporting both SSH 1 and 2).

**Comment by Frky** [comment]
This is yet another choice we have to make: we could also "support" (*i.e.*, answer to) any version of `SSH` (*e.g.*, `SSH-2022.01-HNY`).

Do you think we should only answer to "valid" versions (as an implementation like `OpenSSH` would do) or be open to any version number?

**Comment by p-l-** [comment]
It depends. Maybe we want something configurable?

Anyway we should answer `SSH-1.99-*` the same way than we answer `SSH-2.0-*`.

**Comment by Frky** [comment]
The suggestion has been taken into account, now answers to `SSH-1.99` as well.

**Review by p-l- — APPROVED** [review]

**Pull request merged**
